# Generated by Django 5.2.1 on 2025-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Job must be approved by admin before it is visible to job seekers'),
        ),
    ]
