# Generated by Django 5.2.1 on 2025-09-03 01:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_name_user_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
