# Generated by Django 5.2.1 on 2025-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('job_application', 'Job Application'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('application_status', 'Application Status')], default='info', max_length=20),
        ),
    ]
